name: schemani
description: Simple and extensible data schema validation.
version: 0.0.1-alpha.1
author: Jari Pekkala <jari@vantage.fi>
homepage: https://vantage.fi

environment:
  sdk: ">=2.1.0 <3.0.0"

dev_dependencies:
  test: ^1.8.0
