name: schemani
description: Simple and extensible data schema validation.
version: 0.0.1-alpha.1
author: Jari Pekkala <jari@vantage.fi>
homepage: https://vantage.fi

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

